### ISSUE TITLE
Create a carasoule view of all core members

### ISSUE THREAD

**Issue by jo780-full** [IEEE-DSCE/ieee_ras_dsce_page#5]

**Comment by jo780-full** [comment]
please create a carasoule view

**Comment by MASHOD0** [comment]
# Description
To create a carousel view for displaying the faculty coordinator and the core members.

implementation: @Rida228
integration: @manishgowdans2

**Comment by MASHOD0** [comment]
@Rida228  use this template:

# Implementation 
## javascript file
to be saved as `carousel.js`
```javascript
// javascript code here
```
## CSS
to be put in `style.css`
```css
/* css code here */
```
## HTML
to be put in `index.html`
```html
<!-- html code here -->
```
